name: Lint

on: [push]

jobs:
  oxlint:
    name: Lint TS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx --yes oxlint@1.22.0 --deny-warnings
  nextlint:
    name: Lint Next.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx --yes next lint
